minimumReleaseAge: 10080
minimumReleaseAgeIgnoreMissingTime: false
trustLockfile: false
strictDepBuilds: true
allowBuilds:
  '@prisma/client': true
  '@prisma/engines': true
  prisma: true
  sharp: true
  unrs-resolver: true
