'use client';
import React,{useState,useEffect,useCallback} from 'react';
import {usePathname,useRouter,useSearchParams} from 'next/navigation';
import {adminNotice} from '../lib/policy';
type Data=Record<string,any>;
async function api(path:string,body?:unknown,method?:string){const res=await fetch('/api/'+path,{method:method||(body?'POST':'GET'),headers:body?{'Content-Type':'application/json'}:{},body:body?JSON.stringify(body):undefined,cache:'no-store'});const data=await res.json();if(!res.ok)throw new Error(data.error||'Request failed');return data;}
const money=(value:unknown)=>new Intl.NumberFormat('en-IN',{style:'currency',currency:'INR',maximumFractionDigits:2}).format(Number(value||0));
const date=(value:string)=>new Date(value).toLocaleString('en-IN');
function Empty({text='Nothing here yet.'}:{text?:string}){return <div className="empty">{text}</div>}
function Field({name,label,type='text',value,required=true,...props}:any){return <label>{label||name}<input name={name} type={type} defaultValue={value} required={required} {...props}/></label>}
function Form({children,onSubmit,className='form',label='Save'}:{children:React.ReactNode;onSubmit:(data:Data)=>Promise<void>;className?:string;label?:string}){const [busy,setBusy]=useState(false),[error,setError]=useState('');return <form className={className} onSubmit={async e=>{e.preventDefault();setBusy(true);setError('');const data=Object.fromEntries(new FormData(e.currentTarget));try{await onSubmit(data)}catch(e){setError((e as Error).message)}finally{setBusy(false)}}}>{children}{error&&<div className="error full" role="alert">{error}</div>}<button disabled={busy} className="full">{busy?'Saving…':label}</button></form>}
function Totals({q}:{q:any}){return q?<div className="summary panel">{[['Subtotal',q.subtotal],['Coupon savings',-q.discount],['GST included',q.tax],['Delivery',q.shipping],['Grand total',q.total]].map(([l,v],i)=><div key={String(l)} className={i===4?'total':''}><span>{l}</span><span>{money(Number(v)/100)}</span></div>)}<p><small>Prices include GST. Included GST is not added again.</small></p></div>:null}
export default function Store(){
 const path=usePathname(),router=useRouter(),params=useSearchParams();
 const [user,setUser]=useState<Data|null>(null),[settings,setSettings]=useState<Data>({business:{name:'Shree Hari Kitchen Mart'}}),[categories,setCategories]=useState<Data[]>([]),[brands,setBrands]=useState<Data[]>([]),[data,setData]=useState<any>(null),[error,setError]=useState(''),[busy,setBusy]=useState(true),[message,setMessage]=useState(''),[query,setQuery]=useState(''),[suggestions,setSuggestions]=useState<Data[]>([]),[variant,setVariant]=useState(''),[quantity,setQuantity]=useState(1),[coupon,setCoupon]=useState(''),[quote,setQuote]=useState<any>(null),[addresses,setAddresses]=useState<Data[]>([]),[delivery,setDelivery]=useState('STANDARD'),[addressId,setAddressId]=useState(''),[gateway,setGateway]=useState('COD'),[edit,setEdit]=useState<Data|null>(null),[payBusy,setPayBusy]=useState(false);
 const admin=path.startsWith('/admin');const section=path.split('/')[2]||'dashboard';
 const notify=(s:string)=>{setMessage(s);setTimeout(()=>setMessage(''),4500)};
 const act=async(fn:()=>Promise<any>,success='Saved')=>{try{await fn();notify(success);}catch(e){setError((e as Error).message);}};
 const refresh=useCallback(async()=>{
  setBusy(true);setError('');setEdit(null);
  try{
   const [u,s,c,b]=await Promise.all([api('auth/me'),api('settings'),api('categories'),api('brands')]);setUser(u);setSettings(s);setCategories(c);setBrands(b);
   let endpoint='';
   if(admin){if(!u)throw new Error('Please sign in to access administration.');if(!u.roles.some((r:string)=>['ADMIN','SUPER_ADMIN'].includes(r)))throw new Error('Administrator access required.');endpoint='admin/'+(section==='products'&&path.endsWith('/add')?'products':path.slice(7)||'dashboard');}
   else if(path.startsWith('/product/'))endpoint='products/'+path.split('/')[2];
   else if(['/','/search','/deals','/new-arrivals','/best-sellers'].includes(path)||path.startsWith('/category/')||path.startsWith('/brand/')){const p=new URLSearchParams(params.toString());if(path.startsWith('/category/'))p.set('category',path.split('/')[2]);if(path.startsWith('/brand/'))p.set('brand',path.split('/')[2]);if(path==='/deals')p.set('discount','10');endpoint='products?'+p.toString();}
   else if(path==='/cart'||path==='/checkout')endpoint=u?'cart':'';
   else if(path==='/wishlist'||path==='/account/wishlist')endpoint='wishlist';
   else if(path==='/compare')endpoint='compare';
   else if(path.startsWith('/account/orders/'))endpoint='orders/'+path.split('/')[3];
   else if(path==='/order-success'||path==='/payment/success')endpoint='orders/'+params.get('order');
   else if(path==='/account'||['orders','invoices'].includes(section)&&path.startsWith('/account/'))endpoint='orders';
   else if(path.startsWith('/account/'))endpoint=section==='settings'?'auth/me':section;
   if(endpoint){const result=await api(endpoint);setData(result);if(path.startsWith('/product/')){setVariant(result.variants[0]?.id||'');setQuantity(1);}}else setData(null);
   if(path==='/checkout'){const list=await api('addresses');setAddresses(list);setAddressId(list[0]?.id||'');}
  }catch(e){setError((e as Error).message);setData(null);}finally{setBusy(false);}
 },[path,params,admin,section]);
 useEffect(()=>{refresh()},[refresh]);
 useEffect(()=>{if(query.length<2){setSuggestions([]);return;}let current=true;const timer=setTimeout(()=>api('products?q='+encodeURIComponent(query)).then(r=>{if(current)setSuggestions(r.slice(0,5))}).catch(()=>{}),300);return()=>{current=false;clearTimeout(timer)}},[query]);
 useEffect(()=>{if((path==='/cart'||path==='/checkout')&&data?.some?.((i:Data)=>!i.saved)){api('cart/quote',{code:coupon,delivery}).then(r=>setQuote(r.totals)).catch(e=>{setQuote(null);setError(e.message)})}else setQuote(null)},[path,data,coupon,delivery]);
 const add=async(product:Data,variantId?:string,qty=1)=>{const v=variantId||product.variants[0]?.id;if(!v)throw new Error('Select an available variant');if(!user){const local=JSON.parse(localStorage.getItem('shk_guest_cart')||'[]');const item=local.find((i:Data)=>i.variantId===v);if(item)item.quantity=Math.min(20,item.quantity+qty);else local.push({variantId:v,quantity:qty});localStorage.setItem('shk_guest_cart',JSON.stringify(local));notify('Saved to guest cart. Sign in to checkout.');return;}const cart=await api('cart');const existing=cart.find((i:Data)=>i.variantId===v);await api('cart',{variantId:v,quantity:Math.min(20,(existing?.quantity||0)+qty)});notify('Added to cart');};
 const requireLogin=()=>{if(!user){router.push('/login?next='+encodeURIComponent(path));return false;}return true;};
 const loginDone=async()=>{const local=JSON.parse(localStorage.getItem('shk_guest_cart')||'[]');if(local.length){await api('cart/merge',{items:local});localStorage.removeItem('shk_guest_cart');}const next=params.get('next');router.push(next?.startsWith('/')&&!next.startsWith('//')?next:'/account');};
 const wishlist=(productId:string)=>act(async()=>{if(requireLogin())await api('wishlist',{productId})},'Added to wishlist');
 const compare=(productId:string)=>act(async()=>{if(requireLogin())await api('compare',{productId})},'Added to comparison');
 function Cards({products}:{products:Data[]}){return products?.length?<div className="grid">{products.map(p=>{const v=p.variants?.find((v:Data)=>v.active)||p.variants?.[0],rating=p.reviews?.length?(p.reviews.reduce((s:number,r:Data)=>s+r.rating,0)/p.reviews.length).toFixed(1):null;return <article className="card" key={p.id}><a href={'/product/'+p.slug}>{p.images?.[0]?<img src={p.images[0].url} alt={p.images[0].alt}/>:<div className="product-head"><strong>{p.category?.name}</strong><span>{v?.capacity||p.brand?.name}</span></div>}</a><small>{p.brand?.name} · {v?.sku}</small><a href={'/product/'+p.slug}><h3>{p.name}</h3></a><p className="price">{money(v?.price)}{Number(v?.mrp)>Number(v?.price)&&<del>{money(v?.mrp)}</del>}</p>{rating&&<small>★ {rating} · {p.reviews.length} reviews</small>}<div className="actions"><button onClick={()=>act(()=>add(p))}>Add to cart</button><button className="secondary" onClick={()=>wishlist(p.id)}>Wishlist</button><button className="secondary" onClick={()=>compare(p.id)}>Compare</button></div></article>})}</div>:<Empty text="No matching products. Try a different search or filter."/>}
 function AddressForm({initial}:{initial?:Data}){return <Form className="form two" onSubmit={async values=>{await api('addresses',{...values,...(initial?{id:initial.id}:{})});setEdit(null);if(path==='/checkout'){const list=await api('addresses');setAddresses(list);setAddressId(list[list.length-1]?.id)}else await refresh();notify('Address saved')}}>{['name','phone','line1','line2','city','state','postalCode'].map(n=><Field key={n} name={n} label={{line1:'Street address',line2:'Apartment / landmark',postalCode:'PIN code',name:'Full name',phone:'Mobile number',city:'City',state:'State'}[n]} value={initial?.[n]} required={n!=='line2'}/>)}</Form>}
 async function checkout(){setError('');let key=sessionStorage.getItem('shk_checkout_key');if(!key){key=crypto.randomUUID();sessionStorage.setItem('shk_checkout_key',key);}const result=await api('checkout',{addressId,code:coupon,delivery,gateway,requestKey:key});if(result.order){sessionStorage.removeItem('shk_checkout_key');router.push('/order-success?order='+result.order.id);return;}
  await new Promise<void>((resolve,reject)=>{if((window as any).Razorpay)return resolve();const script=document.createElement('script');script.src='https://checkout.razorpay.com/v1/checkout.js';script.onload=()=>resolve();script.onerror=()=>reject(new Error('Could not load secure payment checkout'));document.body.appendChild(script)});
  const modal=new (window as any).Razorpay({key:result.key,order_id:result.gatewayOrderId,amount:result.amount,currency:'INR',name:settings.business.name,prefill:{name:user?.name,email:user?.email},handler:async(response:Data)=>{try{const verified=await api('payments/verify',{checkoutId:result.checkoutId,...response});sessionStorage.removeItem('shk_checkout_key');router.push('/payment/success?order='+verified.order.id)}catch(e){setError((e as Error).message)}},modal:{ondismiss:()=>notify('Payment was not completed. Your order is not marked paid.')}});modal.on('payment.failed',()=>router.push('/payment/failed'));modal.open();
 }
 function OrderView({order}:{order:Data}){return <div className="stack"><div className="panel"><h2>Order {order.number}</h2><p>{date(order.createdAt)} · {order.status.replaceAll('_',' ')} · {order.paymentStatus}</p><p className="price">{money(order.total)}</p><a className="button" href={'/api/orders/'+order.id+'/invoice'}>Download PDF invoice</a></div><div className="panel"><h2>Items</h2>{order.items?.map((i:Data)=><div className="row" key={i.id}><div><h3>{i.name}</h3><small>{i.variant} · {i.sku} · Quantity {i.quantity}</small></div><span>{money(i.unitPrice)}</span></div>)}</div><div className="panel"><h2>Order tracking</h2><div className="timeline">{order.history?.map((h:Data)=><div key={h.id}><strong>{h.status.replaceAll('_',' ')}</strong><p>{h.note}<br/><small>{date(h.createdAt)}</small></p></div>)}</div>{order.shipments?.map((s:Data)=><p key={s.id}>Carrier: {s.carrier} · Tracking: {s.trackingNumber}</p>)}</div>{order.status==='DELIVERED'&&<div className="panel"><h2>Review your purchase</h2><Form label="Submit review for moderation" onSubmit={async v=>{await api('reviews',{...v,rating:Number(v.rating)});notify('Review submitted')}}><label>Product<select name="productId">{order.items.map((i:Data)=><option value={i.productId} key={i.id}>{i.name}</option>)}</select></label><label>Rating<select name="rating">{[5,4,3,2,1].map(n=><option key={n}>{n}</option>)}</select></label><Field name="title" label="Review title"/><label>Your review<textarea name="body" required/></label></Form><h2>Request a return</h2><Form label="Submit return request" onSubmit={async v=>{await api('returns',{orderId:order.id,reason:v.reason,resolution:'REFUND',items:[{orderItemId:v.orderItemId,quantity:Number(v.quantity)}]});notify('Return requested');await refresh()}}><label>Item<select name="orderItemId">{order.items.map((i:Data)=><option value={i.id} key={i.id}>{i.name}</option>)}</select></label><Field name="quantity" type="number" value="1" min="1"/><Field name="reason" label="Reason for return"/></Form></div>}</div>}
 function ProductForm({product}:{product?:Data}){const v=product?.variants?.[0];return <div className="panel"><div className="notice">{adminNotice}</div><Form className="form two" label="Save product" onSubmit={async values=>{const {sku,variantName,price,mrp,gstRate,capacity,wattage,material,...rest}=values;await api('admin/products'+(product?'/'+product.id:''),{...rest,active:rest.active==='on',vegetarianConfirmed:rest.vegetarianConfirmed==='on',variant:{sku,name:variantName,price:Number(price),mrp:Number(mrp),gstRate:Number(gstRate),capacity,wattage:Number(wattage),material}});await refresh();router.push('/admin/products')}}>{['name','slug','warranty','keywords','seoTitle','seoDescription'].map(n=><Field key={n} name={n} value={product?.[n]||''} required={['name','slug','warranty'].includes(n)}/>)}<label className="full">Description<textarea name="description" defaultValue={product?.description} required/></label><label>Category<select name="categoryId" defaultValue={product?.categoryId}>{categories.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label><label>Brand<select name="brandId" defaultValue={product?.brandId}>{brands.map(b=><option key={b.id} value={b.id}>{b.name}</option>)}</select></label>{['sku','variantName','price','mrp','gstRate','capacity','wattage','material'].map(n=><Field key={n} name={n} value={n==='variantName'?v?.name:v?.[n]??(n==='gstRate'?18:n==='wattage'?0:'')} type={['price','mrp','gstRate','wattage'].includes(n)?'number':'text'} step="0.01" required={!['capacity','material'].includes(n)}/>)}<label className="check full"><input type="checkbox" name="vegetarianConfirmed" required/>Confirm this product and its marketing content contain no non-vegetarian or egg-related imagery or descriptions.</label><label className="check"><input type="checkbox" name="active" defaultChecked={product?.active}/>Publish product</label></Form></div>}
 function Admin(){
  if(!data)return null;
  if(section==='dashboard')return <><h1>Store overview</h1><div className="grid">{[['Revenue',money(data.revenue)],['Orders',data.orders],['Customers',data.customers],['Average order',money(data.averageOrderValue)],['Today',money(data.todayRevenue)],['Products',data.products],['Returns',data.returns],['Refunds',money(data.refunds)]].map(([l,v])=><div className="panel" key={l}><small>{l}</small><strong className="metric">{v}</strong></div>)}</div><h2>Recent orders</h2><OrderTable orders={data.recent} isAdmin/><h2>Low stock</h2>{data.lowStock?.map((i:Data)=><p key={i.id}>{i.variant.product.name}: {i.quantity-i.reserved} available</p>)}</>;
  if(section==='products'){if(path.endsWith('/add'))return <><h1>Add product</h1><ProductForm/></>;if(!Array.isArray(data))return <><h1>Edit product</h1><ProductForm product={data}/><h2>Product images</h2><Form label="Add reviewed image" onSubmit={async v=>{await api('admin/images',{...v,productId:data.id,vegetarianConfirmed:true,imageReviewed:v.imageReviewed==='on'});await refresh()}}><Field name="url" type="url" label="HTTPS image URL"/><Field name="alt" label="Image description"/><label className="check"><input name="imageReviewed" type="checkbox" required/>I inspected this image and confirmed vegetarian compliance.</label></Form>{data.images.map((i:Data)=><div className="row" key={i.id}><span>{i.alt}</span><button onClick={()=>act(async()=>{await api('admin/images',{id:i.id},'DELETE');await refresh()})}>Delete image</button></div>)}</>;
   return <><div className="toolbar"><h1>Products</h1><a className="button" href="/admin/products/add">Add product</a></div><div className="table-wrap panel"><table><thead><tr><th>Name</th><th>Category</th><th>Visibility</th><th>Actions</th></tr></thead><tbody>{data.map((p:Data)=><tr key={p.id}><td>{p.name}</td><td>{p.category.name}</td><td>{p.active?'Published':'Disabled'}</td><td className="actions"><a className="button secondary" href={'/admin/products/'+p.id}>Edit</a><button onClick={()=>act(async()=>{await api('admin/products/'+p.id,{},'DELETE');await refresh()})}>Disable</button></td></tr>)}</tbody></table></div></>;}
  if(section==='orders'){if(Array.isArray(data))return <><h1>Orders</h1><OrderTable orders={data} isAdmin/></>;return <><OrderView order={data}/><h2>Update fulfillment</h2><Form onSubmit={async v=>{await api('admin/orders/'+data.id,{...v,codCollected:v.codCollected==='on'});await refresh()}}><label>Next status<select name="status">{['PROCESSING','PACKED','SHIPPED','OUT_FOR_DELIVERY','DELIVERED','CANCELLED'].map(s=><option key={s}>{s}</option>)}</select></label><Field name="note" required={false}/><Field name="carrier" required={false}/><Field name="trackingNumber" label="Tracking number" required={false}/><label className="check"><input type="checkbox" name="codCollected"/>Cash on delivery payment collected</label></Form></>;}
  if(section==='inventory')return <><h1>Inventory</h1><div className="stack">{data.map((i:Data)=><div className="panel" key={i.id}><h3>{i.variant.product.name} · {i.variant.sku}</h3><p>{i.warehouse.name}: {i.quantity} on hand · {i.reserved} reserved</p><Form label="Record adjustment" onSubmit={async v=>{await api('admin/inventory',{id:i.id,delta:Number(v.delta),reason:v.reason});await refresh()}}><Field name="delta" label="Quantity adjustment (+ / −)" type="number"/><Field name="reason"/></Form></div>)}</div></>;
  if(section==='categories'||section==='brands')return <><h1>{section==='categories'?'Categories':'Brands'}</h1><Form onSubmit={async v=>{await api('admin/'+section,v);await refresh()}}><Field name="name"/><Field name="slug"/></Form><div className="stack">{data.map((v:Data)=><div className="row" key={v.id}>{v.name}<small>{v.slug}</small></div>)}</div></>;
  if(section==='settings')return <><h1>Business settings</h1><Form onSubmit={async v=>{await api('admin/settings',v);await refresh();notify('Store settings updated')}}>{['name','address','gstin','supportEmail'].map(n=><Field key={n} name={n} value={data[n]} required={n!=='gstin'}/>)}</Form></>;
  if(section==='delivery')return <><h1>Delivery coverage</h1><Form onSubmit={async v=>{await api('admin/delivery',{enabled:v.enabled==='on',pinCodes:v.pinCodes.split(/[\s,]+/).filter(Boolean),standardDays:v.standardDays,expressDays:v.expressDays});await refresh()}}><label className="check"><input type="checkbox" name="enabled" defaultChecked={data.enabled}/>Enable delivery to the listed PIN codes</label><label>Serviceable PIN codes, separated by commas<textarea name="pinCodes" defaultValue={data.pinCodes?.join(', ')} required/></label><Field name="standardDays" label="Standard delivery estimate" value={data.standardDays}/><Field name="expressDays" label="Express delivery estimate" value={data.expressDays}/></Form></>;
  if(section==='support')return <><h1>Customer support</h1>{data.map((t:Data)=><div className="panel" key={t.id}><h3>{t.subject} · {t.user.name}</h3>{t.messages.map((m:Data)=><p key={m.id}><strong>{m.staff?'Store team':'Customer'}: </strong>{m.body}</p>)}<Form label="Send response" onSubmit={async v=>{await api('admin/support',{id:t.id,...v});await refresh()}}><label>Response<textarea name="body" required/></label><label>Status<select name="status"><option>WAITING_CUSTOMER</option><option>RESOLVED</option><option>OPEN</option></select></label></Form></div>)}</>;
  if(section==='reviews')return <><h1>Review moderation</h1>{data.map((r:Data)=><div className="panel" key={r.id}><h3>{r.product.name} · {r.rating}/5</h3><p>{r.title}: {r.body}</p><p>{r.status}</p><div className="actions">{['APPROVED','REJECTED'].map(status=><button key={status} onClick={()=>act(async()=>{await api('admin/reviews',{id:r.id,status});await refresh()})}>{status==='APPROVED'?'Approve':'Reject'}</button>)}</div></div>)}</>;
  if(section==='coupons')return <><h1>Coupons</h1><Form className="form two" onSubmit={async v=>{await api('admin/coupons',{...v,active:true,restrictions:{},maximum:v.maximum?Number(v.maximum):null});await refresh()}}><Field name="code"/><label>Type<select name="type"><option>PERCENT</option><option>FIXED</option></select></label>{['value','minimum','maximum','usageLimit','perCustomerLimit'].map(n=><Field key={n} name={n} type="number" value={n==='perCustomerLimit'?1:undefined} required={n!=='maximum'}/>)}<Field name="expiresAt" type="datetime-local"/></Form>{data.map((c:Data)=><div className="row" key={c.id}><strong>{c.code}</strong><span>{c.value} {c.type} · Used {c.used}/{c.usageLimit}</span><button onClick={()=>act(async()=>{await api('admin/coupons',{...c,active:!c.active});await refresh()})}>{c.active?'Disable':'Enable'}</button></div>)}</>;
  if(section==='returns')return <><h1>Returns</h1>{data.map((r:Data)=><div className="panel" key={r.id}><h3>{r.order.number} · {r.status}</h3><p>{r.reason}</p>{r.items.map((i:Data)=><p key={i.id}>{i.orderItem.name} × {i.quantity}</p>)}<Form onSubmit={async v=>{await api('admin/returns',{id:r.id,...v,restock:v.restock==='on'});await refresh()}}><label>Status<select name="status">{['APPROVED','REJECTED','MORE_INFO','SCHEDULED','RECEIVED'].map(s=><option key={s}>{s}</option>)}</select></label><Field name="note"/><label className="check"><input type="checkbox" name="restock"/>Returned items inspected and sellable; restore stock</label></Form>{r.status==='RECEIVED'&&<button onClick={()=>act(async()=>{await api('admin/refunds',{returnId:r.id});await refresh()},'Refund submitted to provider')}>Start refund</button>}</div>)}</>;
  if(section==='invoices')return <><h1>Invoices</h1>{data.map((i:Data)=><div className="row" key={i.id}><span>{i.number} · {i.order.number}</span><a className="button" href={'/api/orders/'+i.orderId+'/invoice'}>Download PDF</a></div>)}</>;
  if(section==='customers')return <><h1>Customers</h1>{data.map((u:Data)=><div className="row" key={u.id}><span>{u.name}<br/><small>{u.email}</small></span><span>{u.disabled?'Disabled':'Active'}</span>{user?.roles.includes('SUPER_ADMIN')&&<button onClick={()=>act(async()=>{await api('admin/customers',{id:u.id,disabled:!u.disabled});await refresh()})}>{u.disabled?'Enable':'Disable'}</button>}</div>)}</>;
  if(section==='refunds')return <><h1>Refunds</h1>{data.length?data.map((r:Data)=><div className="row" key={r.id}><span>{r.id}<br/>{money(r.amount)}</span><span>{r.status}</span><small>{r.gatewayRefundId}</small></div>):<Empty/>}</>;
  return <Empty text="This section is not available."/>;
 }
 function OrderTable({orders,isAdmin=false}:{orders:Data[];isAdmin?:boolean}){return orders?.length?<div className="panel table-wrap"><table><thead><tr><th>Order</th><th>Date</th><th>Total</th><th>Status</th><th>Details</th></tr></thead><tbody>{orders.map(o=><tr key={o.id}><td>{o.number}</td><td>{date(o.createdAt)}</td><td>{money(o.total)}</td><td>{o.status}<br/><small>{o.paymentStatus}</small></td><td><a className="button secondary" href={(isAdmin?'/admin/orders/':'/account/orders/')+o.id}>View order</a></td></tr>)}</tbody></table></div>:<Empty text="No orders yet."/>}
 let content:React.ReactNode=null;
 if(admin)content=<><nav className="tabs">{['dashboard','products','categories','brands','orders','invoices','customers','inventory','delivery','returns','refunds','coupons','reviews','support','settings'].map(s=><a key={s} className={section===s?'active':''} href={'/admin'+(s==='dashboard'?'':'/'+s)}>{s.replace(/^./,c=>c.toUpperCase())}</a>)}</nav><Admin/></>;
 else if(['/login','/register','/forgot-password','/reset-password'].includes(path))content=<div className="auth panel"><h1>{path==='/register'?'Create account':path==='/login'?'Welcome back':path==='/forgot-password'?'Reset your password':'Choose a password'}</h1><Form label={path==='/login'?'Sign in':path==='/register'?'Create account':'Continue'} onSubmit={async v=>{if(path==='/register'||path==='/login'){await api(path==='/login'?'auth/login':'auth/register',{...v,remember:v.remember==='on'});await loginDone()}else if(path==='/forgot-password'){const r=await api('auth/forgot',v);notify(r.message)}else{await api('auth/reset',{...v,token:params.get('token')});router.push('/login')}}}>{path==='/register'&&<Field name="name" label="Full name"/>}{path!=='/reset-password'&&<Field name="email" label={path==='/login'?'Email or phone':'Email'} type={path==='/login'?'text':'email'}/>} {path!=='/forgot-password'&&<Field name="password" label="Password" type="password" minLength={path==='/login'?undefined:12} maxLength={72}/>} {path==='/login'&&<label className="check"><input type="checkbox" name="remember"/>Remember me</label>}</Form><p><a href="/forgot-password">Forgot password?</a></p><a href={path==='/register'?'/login':'/register'}>{path==='/register'?'Already registered? Sign in':'Create an account'}</a></div>;
 else if(path.startsWith('/product/')&&data){const v=data.variants.find((i:Data)=>i.id===variant),available=v?.inventory.reduce((s:number,i:Data)=>s+i.quantity-i.reserved,0)||0;content=<><div className="detail"><div className="visual panel">{data.images[0]?<img src={data.images[0].url} alt={data.images[0].alt}/>:<><span className="eyebrow">{data.category.name}</span><strong>{data.name}</strong><p>{v?.capacity} · {v?.wattage?`${v.wattage} W`:data.brand.name}</p></>}</div><div><span className="tag">For your vegetarian kitchen</span><h1 style={{marginTop:20}}>{data.name}</h1><p>{data.description}</p><p className="price">{money(v?.price)} <del>{money(v?.mrp)}</del></p><small>Inclusive of GST · {available} available</small><label>Variant<select value={variant} onChange={e=>setVariant(e.target.value)}>{data.variants.map((v:Data)=><option key={v.id} value={v.id}>{v.name}</option>)}</select></label><label>Quantity<input type="number" min="1" max={Math.min(20,available)} value={quantity} onChange={e=>setQuantity(Number(e.target.value))}/></label><div className="actions" style={{marginTop:20}}><button onClick={()=>act(()=>add(data,variant,quantity))}>Add to cart</button><button onClick={()=>act(async()=>{await add(data,variant,quantity);router.push(user?'/checkout':'/login?next=/checkout')})}>Buy now</button><button className="secondary" onClick={()=>wishlist(data.id)}>Wishlist</button><button className="secondary" onClick={()=>compare(data.id)}>Compare</button><button className="secondary" onClick={()=>act(async()=>{if(navigator.share)await navigator.share({title:data.name,url:location.href});else await navigator.clipboard.writeText(location.href)},'Product link shared')}>Share</button></div><p>Warranty: {data.warranty}</p><Form label="Check delivery" onSubmit={async v=>{const coverage=await api('delivery?pin='+encodeURIComponent(v.pin));notify(coverage.available?`Delivery available. Standard: ${coverage.standardDays}; Express: ${coverage.expressDays}`:'Delivery to this PIN code has not been enabled by the store.')}}><Field name="pin" label="Delivery PIN code"/></Form></div></div><h2>Specifications</h2><div className="panel">{data.specifications.map((s:Data)=><div className="row" key={s.id}><span>{s.name}</span><strong>{s.value}</strong></div>)}<div className="row"><span>Material</span><strong>{v?.material}</strong></div></div><h2>Customer reviews</h2>{data.reviews.length?data.reviews.map((r:Data,i:number)=><div className="panel" key={i}><h3>{r.title} · {r.rating}/5</h3><p>{r.body}</p>{r.verified&&<span className="tag">Verified purchase</span>}</div>):<Empty text="No published reviews yet."/>}<h2>Ask about this appliance</h2><Form label="Submit question" onSubmit={async v=>{if(requireLogin()){await api('questions',{productId:data.id,body:v.body});notify('Question submitted')}}}><label>Question<textarea name="body" required/></label></Form></>}
 else if(['/','/search','/deals','/new-arrivals','/best-sellers'].includes(path)||path.startsWith('/category/')||path.startsWith('/brand/'))content=<>{path==='/'&&<section className="hero"><div><div className="eyebrow">Shree Hari · Kitchen essentials</div><h1>A little more joy.<br/>In every preparation.</h1><p>Thoughtful appliances for fresh smoothies, everyday rotis, perfectly cooked dal and everything your vegetarian kitchen creates.</p><a className="button" href="/categories">Explore kitchen appliances</a></div><div className="hero-aside"><strong>Made for your<br/>everyday rituals.</strong><span>From the first cup of tea to the last warm roti.</span><a href="/deals">Explore current offers →</a></div></section>}<div className="toolbar"><h1>{path==='/'?'Kitchen essentials':path==='/deals'?'Current offers':'Find your appliance'}</h1><span className="muted">{Array.isArray(data)?data.length:0} products</span></div><form className="filters" action="/search"><label>Search<input name="q" defaultValue={params.get('q')||''}/></label><label>Category<select name="category" defaultValue={params.get('category')||''}><option value="">All categories</option>{categories.map(c=><option key={c.id} value={c.slug}>{c.name}</option>)}</select></label><label>Brand<select name="brand" defaultValue={params.get('brand')||''}><option value="">All brands</option>{brands.map(b=><option key={b.id} value={b.slug}>{b.name}</option>)}</select></label><label>Maximum price<input name="max" type="number" min="0" defaultValue={params.get('max')||''}/></label><label>Sort<select name="sort" defaultValue={params.get('sort')||'new'}><option value="new">Newest</option><option value="price-asc">Price: low to high</option><option value="price-desc">Price: high to low</option></select></label><button>Apply filters</button><a className="button secondary" href="/search">Clear</a></form><Cards products={data||[]}/></>;
 else if(path==='/categories')content=<><h1>Shop by category</h1><div className="grid">{categories.map(c=><a className="panel" key={c.id} href={'/category/'+c.slug}><h3>{c.name}</h3>Explore collection →</a>)}</div></>;
 else if(path==='/cart')content=<><h1>Your cart</h1>{!user?<div className="panel"><p>Your guest cart is saved on this device. Sign in to check live prices and complete your order.</p><a className="button" href="/login?next=/cart">Sign in and merge cart</a></div>:<div className="columns"><div className="stack">{data?.length?data.map((i:Data)=><div className="panel" key={i.id}><div className="row"><div><h3>{i.variant.product.name}</h3><small>{i.variant.name} · {money(i.variant.price)}{i.saved?' · Saved for later':''}</small></div><div className="quantity"><button aria-label="Decrease quantity" onClick={()=>act(async()=>{await api('cart',{variantId:i.variantId,quantity:i.quantity-1,saved:i.saved});await refresh()})}>−</button>{i.quantity}<button aria-label="Increase quantity" onClick={()=>act(async()=>{await api('cart',{variantId:i.variantId,quantity:i.quantity+1,saved:i.saved});await refresh()})}>+</button></div></div><div className="actions"><button className="secondary" onClick={()=>act(async()=>{await api('cart',{variantId:i.variantId},'DELETE');await refresh()})}>Remove</button><button className="secondary" onClick={()=>act(async()=>{await api('cart',{variantId:i.variantId,quantity:i.quantity,saved:!i.saved});await refresh()})}>{i.saved?'Move to cart':'Save for later'}</button><button className="secondary" onClick={()=>act(async()=>{await api('wishlist',{productId:i.variant.productId});await api('cart',{variantId:i.variantId},'DELETE');await refresh()})}>Move to wishlist</button></div></div>):<Empty text="Your cart is empty."/>}<a href="/search">Continue shopping</a></div><div className="stack"><Totals q={quote}/><Form label="Apply coupon" onSubmit={async v=>{await api('cart/quote',{code:v.code,delivery});setCoupon(v.code)}}><Field name="code" label="Coupon code"/></Form>{coupon&&<button className="secondary" onClick={()=>setCoupon('')}>Remove {coupon}</button>}{quote&&<a className="button" href="/checkout">Proceed to checkout</a>}</div></div>}</>;
 else if(path==='/checkout')content=<><h1>Checkout</h1><div className="columns"><div className="stack"><section className="panel"><h2>1. Delivery address</h2>{addresses.map(a=><label className="check" key={a.id}><input type="radio" name="address" checked={addressId===a.id} onChange={()=>setAddressId(a.id)}/><span>{a.name} · {a.line1}, {a.city} {a.postalCode}</span></label>)}<h3>Add an address</h3><AddressForm/></section><section className="panel"><h2>2. Delivery method</h2><select aria-label="Delivery method" value={delivery} onChange={e=>setDelivery(e.target.value)}><option value="STANDARD">Standard · 5–7 business days</option><option value="EXPRESS">Express · 2–4 business days · ₹149</option></select><h2>3. Payment</h2><select aria-label="Payment method" value={gateway} onChange={e=>setGateway(e.target.value)}><option value="COD">Cash on delivery</option>{settings.onlinePayments&&<option value="RAZORPAY">UPI, cards, net banking or wallets {settings.paymentMode==='TEST'?'(Razorpay test mode)':''}</option>}</select>{!settings.onlinePayments&&<p>Online payments are currently unavailable.</p>}</section></div><div className="stack"><Totals q={quote}/><Form label="Apply coupon" onSubmit={async v=>{await api('cart/quote',{code:v.code,delivery});setCoupon(v.code)}}><Field name="code" label="Coupon code"/></Form><button disabled={payBusy} onClick={async()=>{setPayBusy(true);try{await act(checkout,'Checkout opened')}finally{setPayBusy(false)}}}>{gateway==='COD'?'Place cash-on-delivery order':'Continue to secure payment'}</button></div></div></>;
 else if(path==='/wishlist'||path==='/account/wishlist')content=<><h1>Your wishlist</h1>{data?.length?data.map((i:Data)=><div className="row panel" key={i.productId}><a href={'/product/'+i.product.slug}><h3>{i.product.name}</h3>{money(i.product.variants[0]?.price)}</a><div className="actions"><button onClick={()=>act(async()=>{await add(i.product);await api('wishlist',{productId:i.productId},'DELETE');await refresh()})}>Move to cart</button><button className="secondary" onClick={()=>act(async()=>{await api('wishlist',{productId:i.productId},'DELETE');await refresh()})}>Remove</button></div></div>):<Empty text="Save appliances here to come back to them."/>}</>;
 else if(path==='/compare')content=<><h1>Compare appliances</h1>{data?.length?<div className="panel table-wrap"><table><tbody>{['name','price','brand','capacity','wattage','material','warranty'].map(key=><tr key={key}><th>{key}</th>{data.map((i:Data)=><td key={i.productId}>{key==='price'?money(i.product.variants[0]?.price):key==='brand'?i.product.brand.name:i.product[key]||i.product.variants[0]?.[key]||'—'}</td>)}</tr>)}<tr><th>Actions</th>{data.map((i:Data)=><td key={i.productId}><button onClick={()=>act(()=>add(i.product))}>Add to cart</button><button className="secondary" onClick={()=>act(async()=>{await api('compare',{productId:i.productId},'DELETE');await refresh()})}>Remove</button></td>)}</tr></tbody></table></div>:<Empty text="Select up to four products to compare."/>}</>;
 else if(path==='/payment/failed')content=<div className="panel"><h1>Payment was not completed</h1><p>Your order has not been marked paid. You can return to checkout and try again.</p><a className="button" href="/checkout">Retry checkout</a></div>;
 else if(['/order-success','/payment/success'].includes(path)&&data)content=<><div className="notice"><h2>{data.paymentStatus==='PAID'?'Payment verified. Order confirmed.':'Order confirmed. Pay on delivery.'}</h2></div><OrderView order={data}/></>;
 else if(path==='/track-order')content=<><h1>Track your order</h1><p>Sign in to view secure tracking information for your orders.</p><a className="button" href="/account/orders">Open my orders</a></>;
 else if(path.startsWith('/account')){
  let accountContent:React.ReactNode=null;
  if(path==='/account'||section==='orders'&&!path.split('/')[3])accountContent=<><h1>{path==='/account'?`Welcome, ${user?.name||''}`:'My orders'}</h1><OrderTable orders={data||[]}/></>;
  else if(section==='orders'&&data)accountContent=<OrderView order={data}/>;
  else if(section==='invoices')accountContent=<><h1>My invoices</h1>{data?.map((o:Data)=><div className="row" key={o.id}><span>{o.invoice?.number} · {o.number}</span><a className="button" href={'/api/orders/'+o.id+'/invoice'}>Download PDF</a></div>)}</>;
  else if(section==='addresses')accountContent=<><h1>Saved addresses</h1>{data?.map((a:Data)=><div className="row panel" key={a.id}><div><h3>{a.name}</h3>{a.line1}, {a.city} {a.postalCode}</div><div className="actions"><button onClick={()=>setEdit(a)}>Edit</button><button className="secondary" onClick={()=>act(async()=>{await api('addresses',{id:a.id},'DELETE');await refresh()})}>Delete</button></div></div>)}<h2>{edit?'Edit address':'Add address'}</h2><AddressForm key={edit?.id||'new'} initial={edit||undefined}/></>;
  else if(section==='support')accountContent=<><h1>Customer support</h1><Form label="Create support ticket" onSubmit={async v=>{await api('support',v);await refresh()}}><Field name="subject"/><label>Message<textarea name="body" required/></label></Form><h2>Your conversations</h2>{data?.map((t:Data)=><div className="panel" key={t.id}><h3>{t.subject} · {t.status}</h3>{t.messages.map((m:Data)=><p key={m.id}><strong>{m.staff?'Store team':'You'}: </strong>{m.body}</p>)}<Form label="Send reply" onSubmit={async v=>{await api('support/'+t.id,v);await refresh()}}><label>Reply<textarea name="body" required/></label></Form></div>)}</>;
  else if(section==='notifications')accountContent=<><h1>Notifications</h1>{data?.length?data.map((n:Data)=><div className="row panel" key={n.id}><div><h3>{n.title}</h3><p>{n.body}</p></div>{!n.readAt&&<button onClick={()=>act(async()=>{await api('notifications',{id:n.id});await refresh()})}>Mark read</button>}</div>):<Empty/>}</>;
  else if(section==='settings')accountContent=<><h1>Account settings</h1><p>{user?.name} · {user?.email}</p><h2>Change password</h2><Form label="Change password and sign out" onSubmit={async v=>{await api('auth/password',v);router.push('/login')}}><Field name="current" type="password" label="Current password"/><Field name="password" type="password" label="New password" minLength={12}/></Form></>;
  else if(section==='coupons')accountContent=<><h1>Available coupons</h1>{data?.map((c:Data)=><div className="panel" key={c.id}><h3>{c.code}</h3><p>{c.value} {c.type==='PERCENT'?'% off':'rupees off'} · Minimum {money(c.minimum)}</p><small>Expires {date(c.expiresAt)}. Eligibility checked at checkout.</small><p><button onClick={()=>act(()=>navigator.clipboard.writeText(c.code),'Coupon copied')}>Copy code</button></p></div>)}</>;
  else if(section==='returns')accountContent=<><h1>Returns and refunds</h1>{data?.length?data.map((r:Data)=><div className="panel" key={r.id}><h3>{r.order.number} · {r.status}</h3><p>{r.reason}</p><p>{r.note}</p>{r.refund&&<p>Refund: {money(r.refund.amount)} · {r.refund.status}</p>}</div>):<Empty text="Request a return from a delivered order."/>}</>;
  else if(section==='reviews')accountContent=<><h1>My reviews</h1>{data?.length?data.map((r:Data)=><div className="panel" key={r.id}><h3>{r.product.name} · {r.rating}/5</h3><p>{r.body}</p><small>{r.status}</small></div>):<Empty text="Review a delivered purchase from its order details."/>}</>;
  content=<><nav className="tabs">{['orders','invoices','addresses','wishlist','reviews','coupons','returns','notifications','support','settings'].map(s=><a className={section===s?'active':''} href={'/account/'+s} key={s}>{s.replace(/^./,c=>c.toUpperCase())}</a>)}</nav>{accountContent}</>;
 }
 else content=<Empty text="Page not found."/>;
 return <><a href="#main" style={{position:'absolute',left:-9999}}>Skip to content</a><div className="top">Vegetarian kitchen essentials · Your everyday kitchen store</div><header className="header"><div className="header-inner"><a className="logo" href="/">{settings.business.name}<b>Kitchen essentials</b></a><div className="searchbox"><form action="/search"><input name="q" aria-label="Search appliances" placeholder="Search appliances, brands and more" value={query} onChange={e=>setQuery(e.target.value)}/><button>Search</button></form>{suggestions.length>0&&<div className="suggestions">{suggestions.map(p=><a key={p.id} href={'/product/'+p.slug}>{p.name}</a>)}</div>}</div><nav className="nav"><a href={user?'/account':'/login'}>{user?user.name.split(' ')[0]:'Sign in'}</a><a href="/wishlist">Wishlist</a><a href="/cart">Cart</a>{user&&<button className="secondary" onClick={()=>act(async()=>{await api('auth/logout',{});setUser(null);router.push('/login')},'Signed out')}>Logout</button>}</nav></div><nav className="subnav"><a href="/categories">All categories</a><a href="/search">All appliances</a><a href="/deals">Deals</a><a href="/new-arrivals">New arrivals</a><a href="/compare">Compare</a><a href="/track-order">Track order</a><a href="/account/support">Help & support</a>{user?.roles?.some((r:string)=>['ADMIN','SUPER_ADMIN'].includes(r))&&<a href="/admin">Administration</a>}</nav></header><main className="container" id="main">{error&&<div className="error" role="alert">{error}{!user&&<p><a className="button" href={'/login?next='+encodeURIComponent(path)}>Sign in</a></p>}</div>}{busy?<div className="loading" role="status">Loading your store…</div>:content}</main><footer className="footer"><strong>{settings.business.name}</strong><span>Appliances for a vegetarian kitchen.</span><a href="/account/support">Contact support</a></footer>{message&&<div className="toast" role="status">{message}</div>}</>;
}
